version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=requests
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - type: bind
        source: ./db
        target: /var/lib/mysql
    healthcheck:  
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

  extractor:
    container_name: Extractor
    image: extrator:v1.0
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    volumes:
      - type: bind
        source: ./application
        target: /app/Client/logs
